// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"four/app/book/internal/biz"
	"four/app/book/internal/conf"
	"four/app/book/internal/data"
	"four/app/book/internal/server"
	"four/app/book/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	bookRepo := data.NewBookRepo2(logger)
	bookUseCase := biz.NewBookUseCase(bookRepo, logger)
	bookService := service.NewBookService(bookUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, bookService)
	grpcServer := server.NewGRPCServer(confServer, bookService)
	registrar := server.NewRegistrar()
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
